### ISSUE TITLE
Can't seem to add a Condition to a Resource.

### ISSUE THREAD

**Issue by mike-rsi** [seandst/cfn-pyplates#29]
The documentation for class [cfn_pyplates.core.Resource](http://cfn-pyplates.readthedocs.org/en/latest/apiref.html#cfn_pyplates.core.Resource) says you can pass a Condition in the `attributes` parameter, but there doesn't seem to be a class that satisfies the requirements for that object (i.e. the class name `Condition` and a property named `value`, as seen in the `cfn_pyplates.core.Resource._is_attribute` method.)  The class `Condition` that is defined is used for adding Condition items to `cfn_pyplates.core.Conditions`.

I think this could be solved with a class essentially copied from `cfn_pyplates.core.DependsOn` or `cfn_pyplates.core.DeletionPolicy` but I'm not sure what naming convention to use for this new class, as it would make sense to name it `cfn_pyplates.core.Condition`, but that's already used for the above-mentioned purpose.

**Comment by dpiddy** [comment]
Just ran into this and was very confused because the docs [here](http://cfn-pyplates.readthedocs.org/en/latest/apiref.html#cfn_pyplates.core.Resource) and the source [here](http://cfn-pyplates.readthedocs.org/en/latest/_modules/cfn_pyplates/core.html#Condition) make it seems like this should work.

Any plans for a release including this?

**Comment by dpiddy** [comment]
Until then, here's what I added to my pyplate template:

```python
# https://github.com/seandst/cfn-pyplates/issues/29
class Condition(JSONableDict):
    def __init__(self, name, condition):
        super(Condition, self).__init__(condition, name)
        self.value = name
```

**Comment by seandst** [comment]
> Any plans for a release including this?

Not sure if you can see draft releases, but yeah, this is in the next release:
https://github.com/seandst/cfn-pyplates/releases/tag/untagged-a28e905f1174fbaf7acf
