### ISSUE TITLE
Add a method to programmatically generate JSON

### ISSUE THREAD

**Issue by djmitche** [seandst/cfn-pyplates#31]
I'd like to wrap the template generation to also upload to S3 and trigger a deploy.

The `generate` function parses `sys.argv` directly, and then prints its output, so wrapping that would require a lot of futzing (or just calling with subprocess, which is a long way around to invoke a Python function).

Ideally I could just call `cfn_pyplates.core.generate_json(template='mytemplate.py', options={..})` and get a string back.

**Comment by seandst** [comment]
This is handled by #27, which has languished a little. I've got a slightly different version in the works that does this, or something very much like it, that should be up in a few days.

**Comment by djmitche** [comment]
Indeed, a dupe.  Thanks!
