### ISSUE TITLE
Option to reverse engineer pyplates from existing json?

### ISSUE THREAD

**Issue by bedge** [seandst/cfn-pyplates#36]
This is the issue with many of these "save you from cfn json" libs, they are all great in some respect, but none that I've seen so far offer the reverse conversion from json into the python/yaml/whatever source.
I know one cannot create a fully optimized source doc from json, but it's a starting point I'm looking for.
Something that give me a source doc in the tools syntax that I can then refactor and build on without starting from scratch.

**Comment by seandst** [comment]
I am not likely to ever attempt this.

**Comment by bedge** [comment]
Fair enough, I had to ask.

**Comment by seandst** [comment]
This project has a few watchers and contributors, so I won't say it's impossible. I only know for sure that *I* won't be the guy that writes it.

**Comment by devops-dude** [comment]
Now that Designer is so useful in rapidly architecting complex designs this would be a wonderful feature.  If no one else out there goes for it I may attempt this soon.  It could save me a lot of time hand converting to pyplates.
