### ISSUE TITLE
CreationPolicy not supported

### ISSUE THREAD

**Issue by jeffb-stell** [seandst/cfn-pyplates#39]
CreationPolicy is a resource attribute at the Properties / Metadata / UpdatePolicy / DeletionPolicy / DependsOn / Condition level. It's the preferred way to signal resource creation, see http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-creationpolicy.html and http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/deploying.applications.html#deployment-walkthrough-cfn-signal

It would be super keen if a core class could be created to handle this (I'm working around it by directly assigning a JSONableDict to the resource before adding it to the template). If I get time to refactor I'll add and submit a PR, but I'd figure that as unlikely.

**Comment by tehsmyers** [comment]
I failed at github commit refs; this was resolved by #40
